name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "--deny warnings"
  RUSTFLAGS: "--deny warnings"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
            args: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
            args: --all-features
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            toolchain: stable
            args: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            toolchain: nightly
            args: --all-features
          - os: windows-latest
            target: i686-pc-windows-msvc
            toolchain: stable
            args: ""
          - os: windows-latest
            target: i686-pc-windows-msvc
            toolchain: nightly
            args: --all-features
          - os: macos-latest
            target: aarch64-apple-darwin
            toolchain: stable
            args: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            toolchain: nightly
            args: --all-features

    steps:
      - uses: actions/checkout@v6

      - name: Install latest ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --target "${{ matrix.target }}" ${{ matrix.args }}
        
      - name: Test
        run: cargo test --target "${{ matrix.target }}" ${{ matrix.args }}
      
  documentation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly, stable]
    steps:
    - uses: actions/checkout@v6
    - name: Install latest ${{ matrix.toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Generate documentation
      run: cargo doc --all-features
    - name: Install cargo-deadlinks
      run: cargo install cargo-deadlinks
    - name: Check dead links in doc
      run: cargo deadlinks --check-http --ignore-fragments --check-intra-doc-links

  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly, stable]
    steps:
      - uses: actions/checkout@v6
      - name: Install latest ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: ${{ matrix.toolchain }}
            components: clippy
            
      - name: Clippy check
        run: cargo clippy --all-features
          
  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly, stable]
    steps:
    - uses: actions/checkout@v6
    - name: Install latest ${{ matrix.toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt
          
    - name: Format check
      run: cargo fmt --all -- --check
       
  hack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack
        run: cargo hack --feature-powerset check
        
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo install cargo-machete
        uses: taiki-e/install-action@cargo-machete
      - run: cargo machete
        
